**plotly Challenge 2 | Tyler Hilbert | March 24, 2026**

In [43]:
#Installing different libraries
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import json
import pandas as pd
import numpy as np

In [44]:
#Importing the dataset
with open("pokedex.json") as p:
    pokedex = json.load(p)

In [45]:
#Checking the data type we use
type(pokedex)

dict

In [46]:
#Determining what the keys are
pokedex.keys()

dict_keys(['pokemon'])

In [47]:
#determining the type of the pokemon list
type(pokedex["pokemon"])

list

In [48]:
#Determining how many items are in the list
len(pokedex["pokemon"])

151

In [49]:
#Doing a deeper dive and trying to figure out the type of data included within an observation
pokedex["pokemon"][0]

{'id': 1,
 'num': '001',
 'name': 'Bulbasaur',
 'img': 'http://www.serebii.net/pokemongo/pokemon/001.png',
 'type': ['Grass', 'Poison'],
 'height': '0.71 m',
 'weight': '6.9 kg',
 'candy': 'Bulbasaur Candy',
 'candy_count': 25,
 'egg': '2 km',
 'spawn_chance': 0.69,
 'avg_spawns': 69,
 'spawn_time': '20:00',
 'multipliers': [1.58],
 'weaknesses': ['Fire', 'Ice', 'Flying', 'Psychic'],
 'next_evolution': [{'num': '002', 'name': 'Ivysaur'},
  {'num': '003', 'name': 'Venusaur'}]}

In [50]:
#Checking out the keys (again - but this time for the observation)
pokedex["pokemon"][0].keys()

dict_keys(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy', 'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time', 'multipliers', 'weaknesses', 'next_evolution'])

In [51]:
#Making a Data Frame of the pokemon list
pokedata = pd.DataFrame(pokedex["pokemon"])
pokedata.head(5) #checking out the first five observations

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [52]:
#Breaking out types - since some have two types, need to break into two columns
pokedata[["type1","type2"]] = pd.DataFrame(pokedata.type.tolist(), index = pokedata.index) #This is saying make and add two columns - using the type data, turn it into a list. The index keeps the rows intact
pokedata.head(5) #checking out the first five observations

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None

In [53]:
#Tracking the number of types
typegroup = pokedata.groupby("type1").count()["id"] #Making a count of how many instances each type appears in the type1 column - uses the id column
typegroup #calling it to see if it worked

type1
Bug         12
Dragon       3
Electric     9
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      24
Poison      14
Psychic      8
Rock         9
Water       28
Name: id, dtype: int64

In [54]:
#Making a bar chart for types
fig1 = go.Figure(data=[go.Bar(x = typegroup.index, y = typegroup.values)]) #setting the bar chart to use the index and values from typegroup to create the bar chart
fig1.show()

In [55]:
#Creating a color sequence - assigning a color to each type
pokecolors_map = {#Saying to map a color to each type - using hex codes
	'Normal': '#A8A77A',
	'Fire': '#EE8130',
	'Water': '#6390F0',
	'Electric': '#F7D02C',
	'Grass': '#7AC74C',
	'Ice': '#96D9D6',
	'Fighting': '#C22E28',
	'Poison': '#A33EA1',
	'Ground': '#E2BF65',
	'Flying': '#A98FF3',
	'Psychic': '#F95587',
	'Bug': '#A6B91A',
	'Rock': '#B6A136',
	'Ghost': '#735797',
	'Dragon': '#6F35FC',
	'Dark': '#705746',
	'Steel': '#B7B7CE',
	'Fairy': '#D685AD',
}
pokecolors = typegroup.index.map(pokecolors_map) #formally mapping the colors to each type from the typegroup variable - looking at index specifically, not values
pokecolors = list(pokecolors)
pokecolors

['#A6B91A',
 '#6F35FC',
 '#F7D02C',
 '#C22E28',
 '#EE8130',
 '#735797',
 '#7AC74C',
 '#E2BF65',
 '#96D9D6',
 '#A8A77A',
 '#A33EA1',
 '#F95587',
 '#B6A136',
 '#6390F0']

In [56]:
#Adding color to the Type Bar Chart
fig2 = go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values,
 marker_color=pokecolors)]) #setting the colors to align with the pokecolors we set before

fig2.show()

In [57]:
#Making a Pie Chart of Pokemon Types

fig3 = go.Figure(
    data=[
    go.Pie(#Saying we want a pie chart
        labels=typegroup.index, #Calling the typegroup index
        values=typegroup.values, #calling the typegroup values
        marker=dict(colors=pokecolors), #Saying we want the colors to be based off pokecolors
        title="Gen 1 Pokemon by Main Type" #Setting the title of the pie chart
        )])

fig3.show()

In [58]:
#Looking at the end of the data - seeing that we have nulls, want to see what kind of data that is
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None

In [59]:
#Checking the null data type
type(pokedata["next_evolution"][150])

float

In [60]:
#Cleaning up the null data

conditions = [#Listing out the conditions for the variable using numpy
    (pokedata['next_evolution'].apply(isinstance, args=(list,))) & (pokedata['prev_evolution'].apply(isinstance, args=(float,))), #Condition 1 = if next evolution is a list and previous evolution is float
    (pokedata['next_evolution'].apply(isinstance, args=(float,))) & (pokedata['prev_evolution'].apply(isinstance, args=(list,))), #Condition 2 = if next evolution is float and previous evoluation is list
    (pokedata['next_evolution'].apply(isinstance, args=(float,))) & (pokedata['prev_evolution'].apply(isinstance, args=(float,))) #Condition 3 = Both next and previous evoluation are floats
]

choices = ["Starter", "Final", "Lone"] #Assigning an order (Start form, Final Form, No Form)
pokedata['evolution_stage'] = np.select(conditions, choices, default="Middle") #Making a column that runs through the conditions and choices laid out earlier - if none of the conditions are met, put Middle

In [61]:
#Running the tail to see if it worked
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None,Starter
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None,Middle
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying,Final
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone

In [62]:
#Grouping the Evolution Data
evol = pokedata.groupby("evolution_stage").count()["id"]
evol

evolution_stage
Final      56
Lone       25
Middle     16
Starter    54
Name: id, dtype: int64

In [63]:
fig4 = make_subplots(#This is saying this figure should have multiple plots in it
    rows = 1, #One row of figures
    cols = 2, #Two columns of figures
    specs=[[{"type":"domain"},{"type":"domain"}]]) #Setting the types of the figures - domain is used for pie charts. Need 2 since there will be 2 figures

fig4.add_trace(
    go.Pie(#Saying it'll be a pie chart
        labels=typegroup.index, #Calling the index from the type count
        values=typegroup.values, #Calling the values from the type count
        marker=dict(colors=pokecolors), #Recalling the colors from the color chart we made
        title="Gen 1 Pokemon by Main Type" #Setting the title
        ),
        1, 1)#Saying it goes in the first slot
# you can copy and paste this from the other chart
fig4.add_trace( 
    go.Pie( #saying it will be a pie chart
        labels=evol.index,  #calling the index from the evo count
        values=evol.values, #calling the values from the evo count
        title="Gen 1 Pokemon by Evolution Stage" #setting the title
        ),
        1, 2) #say we are going into the second slot

fig4.show()

In [64]:
#Looking at height/weight data (Making a Scatterplot
pokedata.head(1) #Calling this to see the height/weight of the first row

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.69,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter

In [65]:
#Looking at weight type - is a string. Will need to turn into continuous data to work
type(pokedata["weight"][0])

str

In [66]:
#Looking at height type - is a string. Will need to turn into continuous data to work
type(pokedata["height"][0])

str

In [67]:
#Converting weight into numbers/continuous data
pokedata["weight_kg"] = pokedata["weight"].str.replace(" kg","",regex=False)#Saying to make a new column that is weight, but removes the kg. Regex is saying interpret this as a string of text
pokedata["weight_kg"]=pd.to_numeric(pokedata["weight_kg"]) #Updating the column to be numeric data

In [68]:
#Converting height into numbers/continuous data
pokedata['height_m'] = pokedata['height'].str.replace(' m', '', regex=False) #Make a new column for height, minus the m
pokedata['height_m'] = pd.to_numeric(pokedata['height_m']) #Updating the column to be numeric data

pokedata.head() #running to see if it worked

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09

In [69]:
#Building a graph using go.Figure - instead of specifying the figure like go.Pie or go.Bar, we put the components in to build the figure for us instead. Allows more freedom

traces = go.Scatter(#Saying we want the traces to take the form of a scatter plot
                x=pokedata["height_m"], #Saying to pull the height data for x
                    y=pokedata["weight_kg"], #Saying to pull the weight data for y
                    mode="markers") #saying to put markers/dots - not lines or text

layout = go.Layout(#Saying we are controlling the layout
                title=dict(text="Pokemon weight and height"), #This is assigning a title 
                   xaxis=dict(title="Weight (in kg)"), #assigning an x-axis label
                   yaxis=dict(title="Height (in m)")) #assigning a y-axis label

fig5 = go.Figure(data=[traces], layout=layout) #We are plugging in what we made earlier - this allowed us to better control the figure content

fig5.show()

In [70]:
#Making the Figure Pretty

#Start by replicating the traces 4 times - one for each evo stage

trace1 = go.Scatter( #defining trace
                x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                name="Lone") #Assigning the name of the evo stage

trace2 = go.Scatter( #defining trace
                x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                name="Starter") #Again assigning the name of the evo stage

trace3 = go.Scatter( #defining ftrace
                x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                name="Middle") #Again assigning the name of the evo stage

trace4 = go.Scatter( #defining trace
                x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                name="Final") #Again assigning the name of the evo stage

layout = go.Layout(#Saying we are controlling the layout
                title=dict(text="Pokemon weight and height by Evolution Stage"), #This is assigning a title 
                   xaxis=dict(title="Weight (in kg)"), #assigning an x-axis label
                   yaxis=dict(title="Height (in m)")) #assigning a y-axis label

fig6 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout) #Putting the dictionary of traces lets us put all four on the same figure

fig6.update_traces(mode="markers", #This is dictating the style of the scatter plot (telling it to use dots)
                   marker=dict(size=10,opacity=.5)) #Setting the size and opacity of the dots

fig6.show()

In [71]:
#Adding more text to hovering (name and type)

condition = pokedata["type1"].notna() & pokedata["type2"].notna() #Listing condition where both types are not na

pokedata["Types"] = np.where(condition, #Putting the condition here
                             pokedata["type1"] + " & " + pokedata["type2"], #If condition is met, mush both together as a string with a & in between
                             pokedata["type1"]) #If condition isn't met, just put the first type
pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m,Types
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71,Grass & Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99,Grass & Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01,Grass & Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61,Fire
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09,Fire

In [72]:
#Plugging the new data in (to the old figure)

trace1 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Lone"]["name"],#Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Lone"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Lone") #Again assigning the name of the evo stage

trace2 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Starter"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Starter"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Starter") #Again assigning the name of the evo stage

trace3 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Middle"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Middle"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Middle") #Again assigning the name of the evo stage

trace4 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Final"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Final"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Final") #Again assigning the name of the evo stage

layout = go.Layout(#Saying we are controlling the layout
                title=dict(text="Pokemon Weight and Height by Evolution Stage"), #This is assigning a title 
                   xaxis=dict(title="Height (in m)"), #assigning an x-axis label
                   yaxis=dict(title="Weight (in kg)")) #assigning a y-axis label

fig7 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout) #Putting the dictionary of traces lets us put all four on the same figure

fig7.update_traces(
                mode="markers", #This is dictating the style of the scatter plot (telling it to use dots)
                marker=dict(size=10,opacity=.5), #Setting the size and opacity of the dots
                #New Bit Below! Using HTML coding to manually customize the hover text (use {} to put the code). Use the \ to indicate it is continuing
                 hovertemplate="<b>%{customdata}</b> "\
                 "<br>%{text} Type"\
                "<br>Weight: %{y}kg"\
                "<br>Height: %{x}m") 

fig7.show()

In [ ]:
#Making buttons

trace1 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Lone"]["name"],#Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Lone"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Lone") #Again assigning the name of the evo stage

trace2 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Starter"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Starter"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Starter") #Again assigning the name of the evo stage

trace3 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Middle"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Middle"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Middle") #Again assigning the name of the evo stage

trace4 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Final"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Final"]["Types"], #New Bit! Putting the text in for the pokemon types
                name="Final") #Again assigning the name of the evo stage

layout = go.Layout(#Saying we are controlling the layout
                title=dict(text="Pokemon Weight and Height by Evolution Stage"), #This is assigning a title 
                   xaxis=dict(title="Height (in m)"), #assigning an x-axis label
                   yaxis=dict(title="Weight (in kg)")) #assigning a y-axis label

fig7 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout) #Putting the dictionary of traces lets us put all four on the same figure

fig7.update_traces(
                mode="markers", #This is dictating the style of the scatter plot (telling it to use dots)
                marker=dict(size=10,opacity=.5), #Setting the size and opacity of the dots
                #New Bit Below! Using HTML coding to manually customize the hover text (use {} to put the code). Use the \ to indicate it is continuing
                 hovertemplate="<b>%{customdata}</b> "\
                 "<br>%{text} Type"\
                "<br>Weight: %{y}kg"\
                "<br>Height: %{x}m") 

fig7.update_layout(updatemenus = [dict( 
    type = "buttons", #saying we want it buttons
    direction = "left", #saying we want it horizontal on the left side of the screen
    x = 0.5, #setting x origin
    y= 1.15, #setting y origin
    showactive=True, #when you select an option, the button should stay highlighted
    buttons = #helps make it interactable (buttons, horizontal, etc.) - define features in a dictionary
               list([dict(label = "All", #setting the label for the all button
                         method = "update", #telling the figure to update
                        args = [{"visible":[True, True, True, True]}]), #saying this will you see all stages
                     dict(label = "Lone", #setting the label for the Lone ones
                         method = "update", #telling the figure to update
                        args = [{"visible":[True, False, False, False]}]), #saying this will show lone only   
                     dict(label = "Starter", #setting the label to say starter
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, True, False, False]}]), #saying this will show starter only
                     dict(label = "Middle", #setting the label to say middle
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, False, True, False]}]), #saying this will show middle only
                     dict(label = "Final", #setting the label to say final
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, False, False, True]}]), #saying this will show final only     
                        ]))])

fig7.show()

In [76]:
#Making a dropdown menu and adding color to the traces

trace1 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Lone"]["name"],#Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Lone"]["Types"], #New Bit! Putting the text in for the pokemon types
                marker_color = "lightslategray", #can write out color - this changes the marker color for this one
                name="Lone") #Again assigning the name of the evo stage

trace2 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Starter"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Starter"]["Types"], #New Bit! Putting the text in for the pokemon types
                 marker_color = "plum", #can write out color - this changes the marker color for this one
                name="Starter") #Again assigning the name of the evo stage

trace3 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Middle"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Middle"]["Types"], #New Bit! Putting the text in for the pokemon types
                marker_color = "mediumvioletred", #can write out color - this changes the marker color for this one
                name="Middle") #Again assigning the name of the evo stage

trace4 = go.Scatter(#defining trace
                x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], #Saying that x should be the height data only when evo stage matches
                y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"], #Saying that y should be the weight data only when the evo stage matches
                customdata=pokedata[pokedata["evolution_stage"] == "Final"]["name"], #Pulling the name of the evo stage
                text=pokedata[pokedata["evolution_stage"] == "Final"]["Types"], #New Bit! Putting the text in for the pokemon types
                marker_color = "indigo", #can write out color - this changes the marker color for this one
                name="Final") #Again assigning the name of the evo stage

layout = go.Layout(#Saying we are controlling the layout
                title=dict(text="Pokemon Weight and Height by Evolution Stage"), #This is assigning a title 
                   xaxis=dict(title="Height (in m)"), #assigning an x-axis label
                   yaxis=dict(title="Weight (in kg)"),#assigning a y-axis label
                   showlegend = False) #hiding the legend

fig7 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout) #Putting the dictionary of traces lets us put all four on the same figure

fig7.update_traces(
                mode="markers", #This is dictating the style of the scatter plot (telling it to use dots)
                marker=dict(size=10,opacity=.5), #Setting the size and opacity of the dots
                #New Bit Below! Using HTML coding to manually customize the hover text (use {} to put the code). Use the \ to indicate it is continuing
                 hovertemplate="<b>%{customdata}</b> "\
                 "<br>%{text} Type"\
                "<br>Weight: %{y}kg"\
                "<br>Height: %{x}m") 

fig7.update_layout(updatemenus = [dict( 
    direction = "down", #This makes it a dropdown menu
    x = 0.5, #setting x origin
    xanchor = "left", #setting from where the x value comes from
    y= 1.15, #setting y origin
    yanchor = "top", #setting from where the y value comes from
    showactive=True, #when you select an option, the button should stay highlighted
    buttons = #helps make it interactable (buttons, horizontal, etc.) - define features in a dictionary
               list([dict(label = "All", #setting the label for the all button
                         method = "update", #telling the figure to update
                        args = [{"visible":[True, True, True, True]}]), #saying this will you see all stages
                     dict(label = "Lone", #setting the label for the Lone ones
                         method = "update", #telling the figure to update
                        args = [{"visible":[True, False, False, False]}]), #saying this will show lone only   
                     dict(label = "Starter", #setting the label to say starter
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, True, False, False]}]), #saying this will show starter only
                     dict(label = "Middle", #setting the label to say middle
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, False, True, False]}]), #saying this will show middle only
                     dict(label = "Final", #setting the label to say final
                         method = "update", #telling the figure to update
                        args = [{"visible":[False, False, False, True]}]), #saying this will show final only     
                        ]))])

fig7.show()