**plotly Challenge 1 | Tyler Hilbert | March 3, 2026**

In [22]:
#importing the different libraries that we are to use
import plotly as pl
import plotly.express as px
import plotly.io as pio
import pandas as pd

In [23]:
#Reading the file
food = pd.read_csv("daily_food_delivery_orders.csv") #pulling the file into the notebook
food.head() #running .head() to make sure it worked OK

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed

In [24]:
#Making a Bar Chart Pt. 1 (Making the chart)

status_counts = food["restaurant_type"].value_counts().reset_index() #This looks at the restaurant type and counts the number of values in the column
status_counts.columns = ["restaurant_type","frequency"] #this is naming the columns in the new table

fig1 = px.bar(status_counts, #defining the data set we are pulling
              x="restaurant_type", #assigning x
              y="frequency", #assigning y
              title = "Frequency of Restaurant Type",  #putting the title of the table
              labels = {"restaurant_type": "Restaurant Type", "frequency": "Count"}) #changing labels for the x and y values (before colon what is in data, after colon is what will show up in the chart)


fig1.show() #can hover over the bars to show what the bar values are

In [25]:
#Making a Bar Chart Pt. 2 (Beautifying the Bars)

status_counts = food["restaurant_type"].value_counts().reset_index()
status_counts.columns = ["restaurant_type","frequency"]

fig2 = px.bar(status_counts,
              x="restaurant_type", 
              y="frequency",
              title = "Frequency of Restaurant Type",  
              labels = {"restaurant_type": "Restaurant Type", "frequency": "Count"},
              text = "frequency", #automatically assigns text values to the bar
              color = "restaurant_type", #telling it what you are assigning colors to
              color_discrete_sequence = ["brown","#D3885D","red","yellow","green", "orange"])
                 #actually listing out the colors that are being assigned (you put in the order of the array). Can write out the colors or use hex code


fig2.show()

#Can click items on the legend and it wil hide that bar from the visualization

In [26]:
#Making a Line Chart Pt. 1 (First Attempt)

fig3 = px.line(food, #calling the dataset
              x="order_date",  #assigning the x value
              y="order_value", #assigning the y value
              markers=True) #marking that we want markers to appear

fig3.show()

#dataset is messy because there are just so many values - need to cut it down

In [27]:
#Making a line chart Pt. 2 (Doing the dataset)

food20 = food.head(20) #making a subsection of the data set by
food20 #running it to make sure it worked

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed
5,6,2024-03-16,51,Italian,835.75,3.56,85,UPI,3.8,Delayed
6,7,2024-11-20,52,Cafe,771.83,14.37,80,Card,3.7,Delivered
7,8,2024-11-24,52,Chinese,926.20,12.81,19,UPI,4.4,Delayed
8,9,2024-07-23,38,Bakery,548.11,13.54,42,Cash,4.1,Delayed
9,10,2024-07-01,24,Fast Food,177.18,8.15,29,Cash,2.9,Delivered
10,11,2024-09-16,27,Cafe,806.68,5.43,53,Cash,3.1,Cancelled
11,12,2024-08-27,61,Bakery,1193.33,9.68,26,UPI,3.5,Delivered
12,13,2024-01-09,31,Chinese,758.14,1.28,57,Cash,2.9,Delayed
13,14,2024-09-02,47,Cafe,937.07,13.41,88,Wallet,3.8,Cancelled
14,15,2024-08-21,62,Chinese,810.18,12.36,87,Cash,5.0,Delayed
15,16,2024-07-24,38,Bakery,773.12,9.07,50,Wallet,2.8,Cancelled
16,17,2024-04-09,54,Cafe,816.14,10.95,86,UPI,4.8,Delayed
17,18,2024-04-20,43,Cafe,640.60,4.49,50,Cash,4.1,Delayed
18,19,2024-03-01,54,Indian,193.87,4.40,63,UPI,2.8,Delivered
19,20,2024-08-23,23,Chinese,183.09,14.11,52,Cash,2.9,Cancelled

In [28]:
#Making a Line Chart Pt. 3 (Sorting the data)

food20["in_order_dates"] = pd.to_datetime(food["order_date"]) #making a column in food20 that orders the dates in the original data sets
food20.sort_values("in_order_dates", inplace = True) #This copies over the original data frame with the new data set and sorts them in order
food20

#The warning below is just saying this could lead to issues down the line (basically just pandas double-checking and letting you know there is ambiguity)

C:\Users\thilber2\AppData\Local\Temp\ipykernel_24844\3805359317.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\thilber2\AppData\Local\Temp\ipykernel_24844\3805359317.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status,in_order_dates
12,13,2024-01-09,31,Chinese,758.14,1.28,57,Cash,2.9,Delayed,2024-01-09
2,3,2024-02-28,34,Italian,540.82,3.61,70,Wallet,3.4,Cancelled,2024-02-28
18,19,2024-03-01,54,Indian,193.87,4.40,63,UPI,2.8,Delivered,2024-03-01
5,6,2024-03-16,51,Italian,835.75,3.56,85,UPI,3.8,Delayed,2024-03-16
16,17,2024-04-09,54,Cafe,816.14,10.95,86,UPI,4.8,Delayed,2024-04-09
17,18,2024-04-20,43,Cafe,640.60,4.49,50,Cash,4.1,Delayed,2024-04-20
3,4,2024-05-26,65,Cafe,1197.99,3.66,18,Card,4.6,Cancelled,2024-05-26
9,10,2024-07-01,24,Fast Food,177.18,8.15,29,Cash,2.9,Delivered,2024-07-01
8,9,2024-07-23,38,Bakery,548.11,13.54,42,Cash,4.1,Delayed,2024-07-23
15,16,2024-07-24,38,Bakery,773.12,9.07,50,Wallet,2.8,Cancelled,2024-07-24
1,2,2024-08-20,35,Bakery,232.32,5.83,69,Wallet,2.7,Cancelled,2024-08-20
14,15,2024-08-21,62,Chinese,810.18,12.36,87,Cash,5.0,Delayed,2024-08-21
19,20,2024-08-23,23,Chinese,183.09,14.11,52,Cash,2.9,Cancelled,2024-08-23
11,12,2024-08-27,61,Bakery,1193.33,9.68,26,UPI,3.5,Delivered,2024-08-27
13,14,2024-09-02,47,Cafe,937.07,13.41,88,Wallet,3.8,Cancelled,2024-09-02
10,11,2024-09-16,27,Cafe,806.68,5.43,53,Cash,3.1,Cancelled,2024-09-16
4,5,2024-09-21,40,Indian,947.03,12.08,57,UPI,4.9,Delayed,2024-09-21
0,1,2024-11-05,62,Indian,497.51,11.07,79,UPI,3.9,Cancelled,2024-11-05
6,7,2024-11-20,52,Cafe,771.83,14.37,80,Card,3.7,Delivered,2024-11-20
7,8,2024-11-24,52,Chinese,926.20,12.81,19,UPI,4.4,Delayed,2024-11-24

In [29]:
#Making a Line Chart Pt. 4 (Second Attempt)

fig4 = px.line(food20, #calling the reduced dataset
              x="order_date",  #assigning the x value
              y="order_value", #assigning the y value
              color="order_status", #assigning color to the different order statuses - this creates three lines (one for each order type)
              color_discrete_sequence = ["orange","red","green"], #this assigns different colors to the list of orders - this assigns them in order listed, so need to be careful when writing it out
              markers=True) #marking that we want markers to appear

fig4.update_traces(
    marker=dict(
        symbol="diamond", #Changes the marker shape - I had to reference this page https://plotly.com/python/marker-style/ to find the different symbols you can use in Plotly
        color="yellow"), #Assigns a color to the marker
    )

fig4.show()

In [30]:
#Scatter plots in Plotly Express Pt. 1 (Scatter Plot w/o Aesthetics)

fig5 = px.scatter(
    food, #reading from food
    x = "delivery_distance_km", #assigning x value
    y = "delivery_time_minutes" #assigning y value
)

fig5.show()

In [31]:
#Making a Scatter Plot in Plotly Express Pt. 2 (Full Dataset)

fig6 = px.scatter(
    food, #reading from food
    x = "delivery_distance_km", #assigning x value
    y = "delivery_time_minutes", #assigning y value
    color = "delivery_partner_rating", #assigns colors to the different delivery partner ratings - since it is a numerical value, it does it as a gradient
    symbol = "order_status" #assigns a different symbol to each dot based on what order status is
)

fig6.show()

In [32]:
#Making a Scatter Plot in Plotly Express Pt. 3 (Making the Sample Dataset)

foodsample = food.sample(n = 50) #.sample() is a pandas function that takes a random sample equal to the value of n
foodsample.head()

,order_id,order_date,customer_age,restaurant_type,order_value,delivery_distance_km,delivery_time_minutes,payment_method,delivery_partner_rating,order_status
119,120,2024-04-22,19,Indian,1194.94,3.69,68,Cash,4.8,Delivered
2010,2011,2024-11-15,48,Italian,686.55,3.68,37,Wallet,2.8,Delayed
2196,2197,2024-10-05,56,Bakery,760.55,9.36,46,Wallet,3.0,Cancelled
2067,2068,2024-07-06,50,Italian,565.98,1.28,77,Wallet,4.0,Delayed
316,317,2024-10-02,30,Bakery,947.45,4.08,38,Card,3.5,Cancelled

In [33]:
#Making a Scatter Plot in Plotly Express Pt. 4 (Sample Dataset Plot)

fig7 = px.scatter(
    foodsample, #reading from foodsample
    x = "delivery_distance_km", #assigning x value
    y = "delivery_time_minutes", #assigning y value
    color = "delivery_partner_rating", #assigns colors to the different delivery partner ratings - since it is a numerical value, it does it as a gradient
    symbol = "order_status", #assigns a different symbol to each dot based on what order status is
    labels = {"delivery_time_minutes":"Delivery Time (in minutes)","delivery_distance_km":"Delivery Distance (in KM)"}, #changes the label - first is what it is normally, after is what I want it to be
    title = "Delivery Distance vs. Delivery Time" #This is the title of the figure
)

fig7.update_traces(marker = dict(size=20, opacity = 0.5, #this is changing the size and opacity of the dots
                                 line=dict(width=2, color="black"))) #this is changing the borders of the dots - important to note it is still within the marker=dict() listing

fig7.update_layout(legend={"yanchor":"top", "y":0.88, "xanchor":"left", "x":1.13}) 
    #This is adjusting the location of the legend to make it more legible (sets orientation first, location second). X and Y are not pixel counts, they are proportions

fig7.show()

In [34]:
#Making a Histogram Pt. 1 (Colors)

status_colors = { #Kind of similar to what Seaborn group did - assigning colors to values and making a variable
    "Delivered": "#2A9D8F", 
    "Delayed": "#E9C46A",
    "Cancelled": "#E63946"
}

In [35]:
#Making a Histogram Pt. 2 (Age Groups Column)

food["age_group"] = pd.cut( #this is making different groups for the ages instead of writing each one out individually
    food["customer_age"], #referring to what column we are looking at 
    bins=[0, 18, 25, 35, 45, 60, 100], #making hte intervals for the groups and saying "Hey - the first bin is 0-18, second is 18-25, etc." Important to note that it doesn't overlap (18 is in 0-18, not 18-25)
    labels=["<18", "18-25", "26-35", "36-45", "46-60", "60+"] #the different age groups in our figure
)

In [36]:
#Making a Histogram Pt. 3 (Making the Histogram)

PLOT_TEMPLATE = "plotly_white" #This is setting the default style of the figure - there are different kinds and help make a uniform look

fig8 = px.histogram(
    food, #the dataset we are doing
    x="order_value", #the x axis
    color="order_status", #what we want the colors to be based off of
    color_discrete_map=status_colors, #actually assigning the colors (since we defined a variable before, can call it and it will map the values to the colors)
    facet_col="age_group", #breaks the histogram into different figures based on the age group = should end up with 6 figures)
    facet_col_wrap=3, #saying that there should be three columns of figures - will make 2 rows of three
    nbins=30, #This is the one that I was the shakiest on understanding - I think this is formally controlling the number of bars that can be held? I tried turning it off and on to see a difference, but I couldn't find one
    title="Order Value Distribution by Age Group (Faceted) and Status", #sets the title
    labels={"order_value": "Order Value"} #sets the label for order value
)

fig8.update_layout(template=PLOT_TEMPLATE) #This is updating the layour to use the template we disclosed earlier
fig8.show()